#include "Variable.hpp"
#include "../Math/Constants.hpp"

namespace MathLib {
    Variable::Variable(void) {
        EmptyBenchmark
    }
    Variable::Variable(const String& name, const String& dataType, Node* value, bool constant) : name(name), dataType(dataType), value(value), constant(constant) {
        EmptyBenchmark
    }
    Variable::Variable(const String& name, const String& dataType, const String& value, bool constant) : name(name), dataType(dataType), value(new Node(Node::Type::Constant, value)), constant(constant) {
        EmptyBenchmark
    }
    Array<Variable> CreateDefaultVariables(void) {
        StartBenchmark
        const Variable defaultVariables[] = {
            Variable("true", "Bool", "1", true),
            Variable("false", "Bool", "0", true),
            Variable("e", "R", ToString(e), true),
            Variable("pi", "R", ToString(pi), true),
            Variable("tau", "R", ToString(tau), true),
            Variable("logarithmicCapacityOfUnitDisk", "R", ToString(logarithmicCapacityOfUnitDisk), true),
            Variable("regularPaperfoldingSequence", "R", ToString(regularPaperfoldingSequence), true),
            Variable("dottieNumber", "R", ToString(dottieNumber), true),
            Variable("laplaceLimit", "R", ToString(laplaceLimit), true),
            Variable("goldenAngle", "R", ToString(goldenAngle), true),
            Variable("magicAngle", "R", ToString(magicAngle), true),
            Variable("silverRatio", "R", ToString(silverRatio), true),
            Variable("goldenRatio", "R", ToString(goldenRatio), true),
            Variable("superGoldenRatio", "R", ToString(superGoldenRatio), true),
            Variable("plasticRatio", "R", ToString(plasticRatio), true),
            Variable("connectiveConstant", "R", ToString(connectiveConstant), true),
            Variable("keplerBouwkampConstant", "R", ToString(keplerBouwkampConstant), true),
            Variable("wallisConstant", "R", ToString(wallisConstant), true),
            Variable("gaussConstant", "R", ToString(gaussConstant), true),
            Variable("lemniscateConstant", "R", ToString(lemniscateConstant), true),
            Variable("eulerConstant", "R", ToString(eulerConstant), true),
            Variable("erdosBorweinConstant", "R", ToString(erdosBorweinConstant), true),
            Variable("omegaConstant", "R", ToString(omegaConstant), true),
            Variable("aperyConstant", "R", ToString(aperyConstant), true),
            Variable("ramanujanSoldnerConstant", "R", ToString(ramanujanSoldnerConstant), true),
            Variable("secondHermiteConstant", "R", ToString(secondHermiteConstant), true),
            Variable("liouvilleConstant", "R", ToString(liouvilleConstant), true),
            Variable("firstContinuedFractionConstant", "R", ToString(firstContinuedFractionConstant), true),
            Variable("ramanujanConstant", "R", ToString(ramanujanConstant), true),
            Variable("glaisherKinkelinConstant", "R", ToString(glaisherKinkelinConstant), true),
            Variable("catalanConstant", "R", ToString(catalanConstant), true),
            Variable("meisselMertensConstant", "R", ToString(meisselMertensConstant), true),
            Variable("universalParabolicConstant", "R", ToString(universalParabolicConstant), true),
            Variable("cahenConstant", "R", ToString(cahenConstant), true),
            Variable("gelfondConstant", "R", ToString(gelfondConstant), true),
            Variable("secondFavardConstant", "R", ToString(secondFavardConstant), true),
            Variable("gelfondSchneiderConstant", "R", ToString(gelfondSchneiderConstant), true),
            Variable("sierpinskiConstant", "R", ToString(sierpinskiConstant), true),
            Variable("landauRamanujanConstant", "R", ToString(landauRamanujanConstant), true),
            Variable("firstNielsenRamanujanConstant", "R", ToString(firstNielsenRamanujanConstant), true),
            Variable("giesekingConstant", "R", ToString(giesekingConstant), true),
            Variable("bernsteinConstant", "R", ToString(bernsteinConstant), true),
            Variable("tribonacciConstant", "R", ToString(tribonacciConstant), true),
            Variable("brunConstant", "R", ToString(brunConstant), true),
            Variable("twinPrimesConstant", "R", ToString(twinPrimesConstant), true),
            Variable("prouhetThueMorseConstant", "R", ToString(prouhetThueMorseConstant), true),
            Variable("golombDickmanConstant", "R", ToString(golombDickmanConstant), true),
            Variable("fellerTornierConstant", "R", ToString(fellerTornierConstant), true),
            Variable("base10ChampernowneConstant", "R", ToString(base10ChampernowneConstant), true),
            Variable("salemConstant", "R", ToString(salemConstant), true),
            Variable("khinchinConstant", "R", ToString(khinchinConstant), true),
            Variable("levyConstant1", "R", ToString(levyConstant1), true),
            Variable("levyConstant2", "R", ToString(levyConstant2), true),
            Variable("copelandErdosConstant", "R", ToString(copelandErdosConstant), true),
            Variable("millConstant", "R", ToString(millConstant), true),
            Variable("gompertzConstant", "R", ToString(gompertzConstant), true),
            Variable("vanDerPauwConstant", "R", ToString(vanDerPauwConstant), true),
            Variable("artinConstant", "R", ToString(artinConstant), true),
            Variable("porterConstant", "R", ToString(porterConstant), true),
            Variable("lochsConstant", "R", ToString(lochsConstant), true),
            Variable("deVicciTesseractConstant", "R", ToString(deVicciTesseractConstant), true),
            Variable("liebSquareIceConstant", "R", ToString(liebSquareIceConstant), true),
            Variable("nivenConstant", "R", ToString(nivenConstant), true),
            Variable("stephensConstant", "R", ToString(stephensConstant), true),
            Variable("reciprocalFibonacciConstant", "R", ToString(reciprocalFibonacciConstant), true),
            Variable("feigenbaumConstant1", "R", ToString(feigenbaumConstant1), true),
            Variable("chaitinConstant", "R", ToString(chaitinConstant), true),
            Variable("robbinsConstant", "R", ToString(robbinsConstant), true),
            Variable("weierstrassConstant", "R", ToString(weierstrassConstant), true),
            Variable("fransenRobinsonConstant", "R", ToString(fransenRobinsonConstant), true),
            Variable("feigenbaumConstant2", "R", ToString(feigenbaumConstant2), true),
            Variable("secondDuBoisReymondConstant", "R", ToString(secondDuBoisReymondConstant), true),
            Variable("erdosTenenbaumFordConstant", "R", ToString(erdosTenenbaumFordConstant), true),
            Variable("conwayConstant", "R", ToString(conwayConstant), true),
            Variable("hafnerSarnakMcCurleyConstant", "R", ToString(hafnerSarnakMcCurleyConstant), true),
            Variable("backhouseConstant", "R", ToString(backhouseConstant), true),
            Variable("viswanathConstant", "R", ToString(viswanathConstant), true),
            Variable("komornikLoretiConstant", "R", ToString(komornikLoretiConstant), true),
            Variable("embreeTrefethenConstant", "R", ToString(embreeTrefethenConstant), true),
            Variable("heathBrownMorozConstant", "R", ToString(heathBrownMorozConstant), true),
            Variable("mrbConstant", "R", ToString(mrbConstant), true),
            Variable("primeConstant", "R", ToString(primeConstant), true),
            Variable("somosQuadraticRecurrenceConstant", "R", ToString(somosQuadraticRecurrenceConstant), true),
            Variable("foiasConstant", "R", ToString(foiasConstant), true),
            Variable("taniguchiConstant", "R", ToString(taniguchiConstant), true),
        };
        ReturnFromBenchmark(Array<Variable>(defaultVariables, SizeOfArray(defaultVariables)));
    }
}