#include "Variable.hpp"

Variable::Variable(void) {}
Variable::Variable(const String& name, Node* value, bool constant) : name(name), value(value), constant(constant) {}
Variable::Variable(const String& name, const String& value, bool constant) : name(name), value(new Node(Node::Type::Constant, value)), constant(constant) {}
Array<Variable> CreateDefaultVariables(void) {
    const Variable defaultVariables[] = {
        Variable("e", ToString(e), true),
        Variable("pi", ToString(pi), true),
        Variable("tau", ToString(tau), true),
        Variable("logarithmicCapacityOfUnitDisk", ToString(logarithmicCapacityOfUnitDisk), true),
        Variable("regularPaperfoldingSequence", ToString(regularPaperfoldingSequence), true),
        Variable("dottieNumber", ToString(dottieNumber), true),
        Variable("laplaceLimit", ToString(laplaceLimit), true),
        Variable("goldenAngle", ToString(goldenAngle), true),
        Variable("magicAngle", ToString(magicAngle), true),
        Variable("silverRatio", ToString(silverRatio), true),
        Variable("goldenRatio", ToString(goldenRatio), true),
        Variable("superGoldenRatio", ToString(superGoldenRatio), true),
        Variable("plasticRatio", ToString(plasticRatio), true),
        Variable("connectiveConstant", ToString(connectiveConstant), true),
        Variable("keplerBouwkampConstant", ToString(keplerBouwkampConstant), true),
        Variable("wallisConstant", ToString(wallisConstant), true),
        Variable("gaussConstant", ToString(gaussConstant), true),
        Variable("lemniscateConstant", ToString(lemniscateConstant), true),
        Variable("eulerConstant", ToString(eulerConstant), true),
        Variable("erdosBorweinConstant", ToString(erdosBorweinConstant), true),
        Variable("omegaConstant", ToString(omegaConstant), true),
        Variable("aperyConstant", ToString(aperyConstant), true),
        Variable("ramanujanSoldnerConstant", ToString(ramanujanSoldnerConstant), true),
        Variable("secondHermiteConstant", ToString(secondHermiteConstant), true),
        Variable("liouvilleConstant", ToString(liouvilleConstant), true),
        Variable("firstContinuedFractionConstant", ToString(firstContinuedFractionConstant), true),
        Variable("ramanujanConstant", ToString(ramanujanConstant), true),
        Variable("glaisherKinkelinConstant", ToString(glaisherKinkelinConstant), true),
        Variable("catalanConstant", ToString(catalanConstant), true),
        Variable("meisselMertensConstant", ToString(meisselMertensConstant), true),
        Variable("universalParabolicConstant", ToString(universalParabolicConstant), true),
        Variable("cahenConstant", ToString(cahenConstant), true),
        Variable("gelfondConstant", ToString(gelfondConstant), true),
        Variable("secondFavardConstant", ToString(secondFavardConstant), true),
        Variable("gelfondSchneiderConstant", ToString(gelfondSchneiderConstant), true),
        Variable("sierpinskiConstant", ToString(sierpinskiConstant), true),
        Variable("landauRamanujanConstant", ToString(landauRamanujanConstant), true),
        Variable("firstNielsenRamanujanConstant", ToString(firstNielsenRamanujanConstant), true),
        Variable("giesekingConstant", ToString(giesekingConstant), true),
        Variable("bernsteinConstant", ToString(bernsteinConstant), true),
        Variable("tribonacciConstant", ToString(tribonacciConstant), true),
        Variable("brunConstant", ToString(brunConstant), true),
        Variable("twinPrimesConstant", ToString(twinPrimesConstant), true),
        Variable("prouhetThueMorseConstant", ToString(prouhetThueMorseConstant), true),
        Variable("golombDickmanConstant", ToString(golombDickmanConstant), true),
        Variable("fellerTornierConstant", ToString(fellerTornierConstant), true),
        Variable("base10ChampernowneConstant", ToString(base10ChampernowneConstant), true),
        Variable("salemConstant", ToString(salemConstant), true),
        Variable("khinchinConstant", ToString(khinchinConstant), true),
        Variable("levyConstant1", ToString(levyConstant1), true),
        Variable("levyConstant2", ToString(levyConstant2), true),
        Variable("copelandErdosConstant", ToString(copelandErdosConstant), true),
        Variable("millConstant", ToString(millConstant), true),
        Variable("gompertzConstant", ToString(gompertzConstant), true),
        Variable("vanDerPauwConstant", ToString(vanDerPauwConstant), true),
        Variable("artinConstant", ToString(artinConstant), true),
        Variable("porterConstant", ToString(porterConstant), true),
        Variable("lochsConstant", ToString(lochsConstant), true),
        Variable("deVicciTesseractConstant", ToString(deVicciTesseractConstant), true),
        Variable("liebSquareIceConstant", ToString(liebSquareIceConstant), true),
        Variable("nivenConstant", ToString(nivenConstant), true),
        Variable("stephensConstant", ToString(stephensConstant), true),
        Variable("reciprocalFibonacciConstant", ToString(reciprocalFibonacciConstant), true),
        Variable("feigenbaumConstant1", ToString(feigenbaumConstant1), true),
        Variable("chaitinConstant", ToString(chaitinConstant), true),
        Variable("robbinsConstant", ToString(robbinsConstant), true),
        Variable("weierstrassConstant", ToString(weierstrassConstant), true),
        Variable("fransenRobinsonConstant", ToString(fransenRobinsonConstant), true),
        Variable("feigenbaumConstant2", ToString(feigenbaumConstant2), true),
        Variable("secondDuBoisReymondConstant", ToString(secondDuBoisReymondConstant), true),
        Variable("erdosTenenbaumFordConstant", ToString(erdosTenenbaumFordConstant), true),
        Variable("conwayConstant", ToString(conwayConstant), true),
        Variable("hafnerSarnakMcCurleyConstant", ToString(hafnerSarnakMcCurleyConstant), true),
        Variable("backhouseConstant", ToString(backhouseConstant), true),
        Variable("viswanathConstant", ToString(viswanathConstant), true),
        Variable("komornikLoretiConstant", ToString(komornikLoretiConstant), true),
        Variable("embreeTrefethenConstant", ToString(embreeTrefethenConstant), true),
        Variable("heathBrownMorozConstant", ToString(heathBrownMorozConstant), true),
        Variable("mrbConstant", ToString(mrbConstant), true),
        Variable("primeConstant", ToString(primeConstant), true),
        Variable("somosQuadraticRecurrenceConstant", ToString(somosQuadraticRecurrenceConstant), true),
        Variable("foiasConstant", ToString(foiasConstant), true),
        Variable("taniguchiConstant", ToString(taniguchiConstant), true),
    };
    Array<Variable> ret = Array<Variable>(SizeOfArray(defaultVariables));
    for (size_t i = 0; i < ret.GetSize(); i++) ret.At(i) = defaultVariables[i];
    return ret;
}